/**
 * E2E test — CLI channel headless test execution via the stdio bridge.
 *
 * Spawns the local `@forgekitstudio/core-mcp` build in `--stdio --profile
 * Lite` mode (no Godot from the test side) and connects an MCP SDK
 * `Client` over `StdioClientTransport`. The CLI executor inside the
 * server then spawns its own `godot --headless` process to run a tiny
 * GUT suite materialized in a temp project, and parses the
 * `TestReport` JSON line emitted by the post-run hook
 * (`gut_to_test_report_hook.gd`).
 *
 * Scenario:
 *   1. Materialize a temporary Godot project containing two passing
 *      GUT tests under `tests/unit/`. The project symlinks the live
 *      `addons/gut/` and `addons/forgekit_core/` so the post-run hook
 *      can preload `TestReport` and emit the sentinel-wrapped JSON.
 *   2. Spawn `node dist/src/index.js --stdio --profile Lite` and
 *      connect via the MCP SDK `Client`.
 *   3. Call `tools/call tests.run_unit({path: "<tmp>/tests/unit"})`.
 *   4. Parse the `content[0].text` payload as JSON and assert the
 *      response is a well-shaped `TestReport` with `total > 0` and
 *      every test marked `passed`.
 *
 * Validates: Requirements 7.2, 7.3, 12.3.
 *
 * The test gracefully skips when no Godot binary is available; it is a
 * no-op on lanes that cannot install the engine. When Godot is present
 * (CI) the test runs end-to-end through the real `tests.run_unit` tool.
 */

import { existsSync } from 'node:fs';
import { mkdir, mkdtemp, realpath, rm, symlink, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const SERVER_ROOT = resolve(HERE, '..', '..');
const ENTRY_POINT = join(SERVER_ROOT, 'dist', 'src', 'index.js');
const PACKAGE_ROOT = resolve(SERVER_ROOT, '..');
const ADDON_GUT = join(PACKAGE_ROOT, 'addons', 'gut');
const ADDON_FORGEKIT_CORE = join(PACKAGE_ROOT, 'addons', 'forgekit_core');

/** Per-call timeout for `tests.run_unit` — Godot cold-start eats time. */
const RPC_TIMEOUT_MS = 60_000;

interface RunUnitTestReport {
    run_id: string;
    timestamp: string;
    total: number;
    passed: number;
    failed: number;
    tests: Array<{
        name: string;
        status: string;
        duration_ms: number;
        assertions: Array<{
            description: string;
            passed: boolean;
            expected: string;
            actual: string;
        }>;
        failure_message: string;
        stack_trace: string;
    }>;
    suggested_action: string;
}

function godotBinary(): string | null {
    const fromEnv = process.env.GODOT_BIN;
    if (fromEnv !== undefined && fromEnv !== '') {
        return fromEnv;
    }
    if (existsSync('/opt/homebrew/bin/godot')) {
        return '/opt/homebrew/bin/godot';
    }
    return null;
}

/**
 * Materialize a fresh temporary Godot project with two passing GUT
 * tests. Returns the absolute project root.
 */
async function materializeUnitTestProject(): Promise<string> {
    const projectDir = await mkdtemp(join(tmpdir(), 'forgekit-e2e-cli-run-unit-'));

    // project.godot — minimal config so Godot can boot the project headless.
    const projectGodot = [
        '; Auto-generated by cli_run_unit_tests.test.ts.',
        '',
        'config_version=5',
        '',
        '[application]',
        '',
        'config/name="ForgeKit MCP CLI run_unit E2E"',
        'config/features=PackedStringArray("4.3", "Forward Plus")',
        '',
        '[rendering]',
        '',
        'renderer/rendering_method="forward_plus"',
        'renderer/rendering_method.mobile="gl_compatibility"',
        '',
    ].join('\n');
    await writeFile(join(projectDir, 'project.godot'), projectGodot, 'utf8');

    await mkdir(join(projectDir, '.godot'), { recursive: true });
    await writeFile(join(projectDir, '.godot', '.gdignore'), '', 'utf8');

    // Symlink the live `addons/gut/` and `addons/forgekit_core/` so the
    // GUT cmdline driver can preload both the test framework and the
    // `TestReport` adapter that the post-run hook prints.
    await mkdir(join(projectDir, 'addons'), { recursive: true });
    const gutTarget = await realpath(ADDON_GUT);
    await symlink(gutTarget, join(projectDir, 'addons', 'gut'));
    const coreTarget = await realpath(ADDON_FORGEKIT_CORE);
    await symlink(coreTarget, join(projectDir, 'addons', 'forgekit_core'));

    // Two passing tests under tests/unit so the asserted `total > 0`
    // contract holds. GUT test scripts must `extends GutTest` and be
    // named `test_*.gd` by default.
    const testsDir = join(projectDir, 'tests', 'unit');
    await mkdir(testsDir, { recursive: true });
    const testScript = [
        'extends GutTest',
        '',
        'func test_arithmetic_passes() -> void:',
        '\tassert_eq(1 + 1, 2, "1 + 1 must equal 2")',
        '',
        'func test_string_concat_passes() -> void:',
        '\tassert_eq("foo" + "bar", "foobar", "string concat must match")',
        '',
    ].join('\n');
    await writeFile(join(testsDir, 'test_basic.gd'), testScript, 'utf8');

    return projectDir;
}

/**
 * Pre-import the Godot project so GUT's `class_name` declarations
 * (`GutTest`, `GutMain`, ...) are registered in
 * `global_script_class_cache.cfg`. Without this step, `gut_cmdln.gd`
 * aborts with `Some GUT class_names have not been imported`.
 *
 * Equivalent to opening the project once in the editor; the
 * `--import` mode resolves every script and writes the cache, then
 * exits.
 */
async function importGodotProject(godot: string, projectDir: string): Promise<void> {
    await new Promise<void>((resolveImport, rejectImport) => {
        const child = spawn(godot, ['--headless', '--import', '--path', projectDir], {
            stdio: ['ignore', 'pipe', 'pipe'],
        });
        let stdout = '';
        let stderr = '';
        child.stdout?.on('data', (chunk: Buffer) => {
            stdout += chunk.toString('utf8');
        });
        child.stderr?.on('data', (chunk: Buffer) => {
            stderr += chunk.toString('utf8');
        });
        child.once('error', rejectImport);
        child.once('close', (code) => {
            // `--import` historically prints class-cache warnings to
            // stderr but exits 0 once the cache is written. Treat any
            // non-zero exit as a hard failure with full output for
            // diagnosis.
            if (code === 0 || code === null) {
                resolveImport();
                return;
            }
            rejectImport(
                new Error(
                    `godot --import exited with code ${code}\n` +
                    `stdout: ${stdout}\nstderr: ${stderr}`,
                ),
            );
        });
    });
}

interface BridgeHandle {
    client: Client;
    transport: StdioClientTransport;
    teardown(): Promise<void>;
}

/**
 * Spawn the local mcp-server build in stdio mode and return a connected
 * MCP SDK `Client`.
 */
async function startStdioBridge(projectDir: string): Promise<BridgeHandle> {
    if (!existsSync(ENTRY_POINT)) {
        throw new Error(
            `Build artifact missing at ${ENTRY_POINT}. Run \`npm run build\` first.`,
        );
    }
    const env: Record<string, string> = {
        ...(process.env as Record<string, string>),
    };
    const binary = godotBinary();
    if (binary !== null) {
        env.GODOT_BIN = binary;
    }
    // Pin the cwd to the temp project so `tests.run_unit` resolves
    // `addons/gut/gut_cmdln.gd` against the symlinked GUT install.
    const transport = new StdioClientTransport({
        command: process.execPath,
        args: [ENTRY_POINT, '--stdio', '--profile', 'Lite'],
        env,
        cwd: projectDir,
    });
    const client = new Client(
        { name: 'cli-run-unit-e2e', version: '0.0.0' },
        { capabilities: {} },
    );
    await client.connect(transport);

    return {
        client,
        transport,
        async teardown(): Promise<void> {
            try {
                await client.close();
            } catch {
                // ignore
            }
        },
    };
}

const binary = godotBinary();
const describeOrSkip = binary === null ? describe.skip : describe;

describeOrSkip('E2E — CLI channel headless test execution via stdio bridge', () => {
    let projectDir: string;
    let bridge: BridgeHandle;

    beforeAll(async () => {
        projectDir = await materializeUnitTestProject();
        // Pre-import so GUT's `class_name` declarations are present in
        // `.godot/global_script_class_cache.cfg` before `gut_cmdln.gd`
        // is loaded by `tests.run_unit`.
        await importGodotProject(binary as string, projectDir);
        bridge = await startStdioBridge(projectDir);
    }, 120_000);

    afterAll(async () => {
        if (bridge !== undefined) {
            await bridge.teardown();
        }
        if (projectDir !== undefined) {
            await rm(projectDir, { recursive: true, force: true }).catch(
                () => undefined,
            );
        }
    });

    it('runs tests.run_unit headless and returns a TestReport with total > 0', async () => {
        const callResult = await bridge.client.callTool(
            {
                name: 'tests.run_unit',
                arguments: { path: 'tests/unit' },
            },
            undefined,
            { timeout: RPC_TIMEOUT_MS },
        );

        // The MCP SDK shapes successful tool calls as
        // `{content: [{type: "text", text: <stringified-result>}]}`.
        // `tests.run_unit` returns a `TestReport` value object.
        expect(callResult.isError).not.toBe(true);
        const content = callResult.content as Array<{ type: string; text: string }>;
        expect(Array.isArray(content)).toBe(true);
        expect(content.length).toBeGreaterThan(0);
        expect(content[0].type).toBe('text');

        let report: RunUnitTestReport;
        try {
            report = JSON.parse(content[0].text) as RunUnitTestReport;
        } catch (err) {
            const detail = err instanceof Error ? err.message : String(err);
            throw new Error(
                `tests.run_unit response was not valid JSON: ${detail}\n` +
                `payload: ${content[0].text}`,
            );
        }

        // TestReport schema sanity — every required field present and
        // typed correctly. The full schema is defined in
        // `src/tools/testing/test_report.ts`.
        expect(typeof report.run_id).toBe('string');
        expect(typeof report.timestamp).toBe('string');
        expect(typeof report.total).toBe('number');
        expect(typeof report.passed).toBe('number');
        expect(typeof report.failed).toBe('number');
        expect(Array.isArray(report.tests)).toBe(true);

        // Acceptance criterion from task 8.20.1.
        expect(
            report.total,
            `Expected total > 0 in ${JSON.stringify(report)}`,
        ).toBeGreaterThan(0);
        expect(report.failed).toBe(0);
        expect(report.passed).toBe(report.total);

        // Both fixture tests should have run.
        const testNames = report.tests.map((t) => t.name);
        const reportSummary = JSON.stringify(report);
        expect(
            testNames.some((n) => n.includes('test_arithmetic_passes')),
            `Expected test_arithmetic_passes in ${reportSummary}`,
        ).toBe(true);
        expect(
            testNames.some((n) => n.includes('test_string_concat_passes')),
            `Expected test_string_concat_passes in ${reportSummary}`,
        ).toBe(true);
        for (const t of report.tests) {
            expect(t.status).toBe('passed');
        }
    }, 90_000);
});
