#!/usr/bin/env node
/**
 * Installer for the ForgeKit Git hooks.
 *
 * Writes two POSIX-shell shim scripts into `<gitDir>/hooks/`:
 *   - `commit-msg`  → executes the compiled Conventional Commits validator.
 *   - `pre-commit`  → executes the compiled Context Commits enforcer.
 *
 * Portability: Git for Windows ships MSYS, so a POSIX shell shim works on
 * every platform Git supports. We therefore emit a single `#!/usr/bin/env sh`
 * shim rather than maintaining two variants.
 *
 * Idempotency rules:
 *   - If a hook file is already a ForgeKit shim (identified by the
 *     {@link FORGEKIT_SHIM_MARKER} string), overwrite it in place.
 *   - If a hook file exists but is not a ForgeKit shim, rename it to
 *     `<name>.backup-<timestampUTC>` and then write the new shim.
 *   - On POSIX platforms, chmod the shim to 0o755. On `win32`, skip chmod.
 */

import {
  chmod as nodeChmod,
  mkdir as nodeMkdir,
  readFile as nodeReadFile,
  rename as nodeRename,
  writeFile as nodeWriteFile,
} from 'node:fs/promises';
import { relative as pathRelative } from 'node:path';

/**
 * Marker line embedded in every ForgeKit shim. Finding this string in an
 * existing hook file means we authored it and can overwrite without backup.
 */
export const FORGEKIT_SHIM_MARKER = '# forgekit-mcp — managed git hook';

/** Minimal filesystem surface used by {@link installHooks}. */
export interface InstallerFs {
  readFile(path: string): Promise<string>;
  writeFile(path: string, contents: string): Promise<void>;
  rename(from: string, to: string): Promise<void>;
  chmod(path: string, mode: number): Promise<void>;
  mkdir(path: string): Promise<void>;
  /** Returns whether the file exists. `false` if it does not. */
  stat(path: string): Promise<boolean>;
}

/** Minimal logger surface. Only used for the non-ForgeKit backup warning. */
export interface InstallerLogger {
  warn(message: string): void;
}

/** Options accepted by {@link installHooks}. */
export interface InstallHooksOptions {
  /** Absolute path to `.git` (e.g. `/repo/.git`). */
  gitDir: string;
  /** Absolute path to the repository root. */
  repoRoot: string;
  /** Absolute path to the compiled `commit-msg.js` script. */
  commitMsgTarget: string;
  /** Absolute path to the compiled `pre-commit.js` script. */
  preCommitTarget: string;
  /** Injected filesystem. Defaults to Node's `fs.promises`. */
  fs?: InstallerFs;
  /** Injected clock. Defaults to `Date.now()`. */
  now?: () => Date;
  /** Injected process platform. Defaults to `process.platform`. */
  platform?: NodeJS.Platform;
  /** Injected logger. Defaults to a `console.warn`-backed implementation. */
  logger?: InstallerLogger;
}

/** Return value of {@link installHooks}. */
export interface InstallHooksResult {
  installed: string[];
  backedUp: string[];
}

function defaultFs(): InstallerFs {
  return {
    readFile: async (path) => nodeReadFile(path, 'utf8'),
    writeFile: async (path, contents) => nodeWriteFile(path, contents, 'utf8'),
    rename: async (from, to) => nodeRename(from, to),
    chmod: async (path, mode) => nodeChmod(path, mode),
    mkdir: async (path) => {
      await nodeMkdir(path, { recursive: true });
    },
    stat: async (path) => {
      try {
        await nodeReadFile(path);
        return true;
      } catch {
        return false;
      }
    },
  };
}

function defaultLogger(): InstallerLogger {
  return {
    warn: (message: string) => {
      // eslint-disable-next-line no-console
      console.warn(message);
    },
  };
}

/**
 * Format a `Date` as a filesystem-safe UTC timestamp:
 * `YYYYMMDDTHHMMSSMMMZ`.
 */
function timestampSuffix(now: Date): string {
  return now.toISOString().replace(/[-:.]/g, '');
}

/**
 * Build the body of a shim script. The shim is deliberately tiny: a shebang,
 * the marker, and a single `exec node` line that forwards all arguments.
 */
function buildShim(repoRoot: string, target: string): string {
  // Use a path relative to the repo root so shims remain stable when the
  // repository is moved to a different location on the same machine.
  const rel = pathRelative(repoRoot, target);
  return [
    '#!/usr/bin/env sh',
    FORGEKIT_SHIM_MARKER,
    '# Auto-generated by `forgekit-mcp install-hooks`. Do not edit by hand.',
    `exec node "$(git rev-parse --show-toplevel)/${rel}" "$@"`,
    '',
  ].join('\n');
}

/**
 * Install a single hook, handling backup/overwrite semantics.
 */
async function installSingleHook(params: {
  fs: InstallerFs;
  logger: InstallerLogger;
  hookPath: string;
  shim: string;
  now: Date;
  skipChmod: boolean;
}): Promise<{ installed: string; backedUp: string | null }> {
  const { fs, logger, hookPath, shim, now, skipChmod } = params;

  const existed = await fs.stat(hookPath);
  let backedUp: string | null = null;
  if (existed) {
    const existing = await fs.readFile(hookPath);
    if (!existing.includes(FORGEKIT_SHIM_MARKER)) {
      const backupPath = `${hookPath}.backup-${timestampSuffix(now)}`;
      await fs.rename(hookPath, backupPath);
      backedUp = backupPath;
      logger.warn(
        `[@forgekitstudio/core-mcp] ${hookPath} already existed and was not authored by ForgeKit. Backed up to ${backupPath}.`,
      );
    }
  }

  await fs.writeFile(hookPath, shim);
  if (!skipChmod) {
    await fs.chmod(hookPath, 0o755);
  }

  return { installed: hookPath, backedUp };
}

/**
 * Install the `commit-msg` and `pre-commit` hooks. See the module header for
 * the full contract.
 */
export async function installHooks(
  options: InstallHooksOptions,
): Promise<InstallHooksResult> {
  const fs = options.fs ?? defaultFs();
  const logger = options.logger ?? defaultLogger();
  const now = options.now ? options.now() : new Date();
  const platform = options.platform ?? process.platform;
  const skipChmod = platform === 'win32';

  const hooksDir = `${options.gitDir}/hooks`;
  await fs.mkdir(hooksDir);

  const plan: Array<{ hookPath: string; target: string }> = [
    {
      hookPath: `${hooksDir}/commit-msg`,
      target: options.commitMsgTarget,
    },
    {
      hookPath: `${hooksDir}/pre-commit`,
      target: options.preCommitTarget,
    },
  ];

  const installed: string[] = [];
  const backedUp: string[] = [];
  for (const entry of plan) {
    const shim = buildShim(options.repoRoot, entry.target);
    const result = await installSingleHook({
      fs,
      logger,
      hookPath: entry.hookPath,
      shim,
      now,
      skipChmod,
    });
    installed.push(result.installed);
    if (result.backedUp !== null) {
      backedUp.push(result.backedUp);
    }
  }

  return { installed, backedUp };
}
